export async function seed(knex) {
  await knex('event').insert([
     { id: 1, date: '2026-04-05', name: 'Midnight Riot', description: 'High energy rock show.', artists: 'Midnight Riot', venue_name: 'The Civic', start_time: '20:00', image_url: 'https://picsum.photos/seed/event1/600/400', ticket_link: 'https://tickets.com/event1', created_by: 1, featured: true, genre: 'rock' },
    { id: 2, date: '2026-04-06', name: 'Neon Pulse', description: 'Electronic DJ night.', artists: 'DJ Pulse', venue_name: 'Underground Lounge', start_time: '21:30', image_url: 'https://picsum.photos/seed/event2/600/400', ticket_link: 'https://tickets.com/event2', created_by: 2, featured: true, genre: 'electronic' },
    { id: 3, date: '2026-04-07', name: 'Indie Garden', description: 'Relaxed indie gig.', artists: 'The Ferns', venue_name: 'Harbour Stage', start_time: '19:00', image_url: 'https://picsum.photos/seed/event3/600/400', ticket_link: 'https://tickets.com/event3', created_by: 1, featured: false, genre: 'rock' },
    { id: 4, date: '2026-04-08', name: 'Urban Flow', description: 'Hip hop showcase.', artists: 'MC Nova', venue_name: 'Bassline Club', start_time: '22:00', image_url: 'https://picsum.photos/seed/event4/600/400', ticket_link: 'https://tickets.com/event4', created_by: 3, featured: false, genre: 'hiphop' },
    { id: 5, date: '2026-04-09', name: 'Blue Note Sessions', description: 'Smooth jazz night.', artists: 'Blue Note Trio', venue_name: 'Velvet Room', start_time: '18:30', image_url: 'https://picsum.photos/seed/event5/600/400', ticket_link: 'https://tickets.com/event5', created_by: 2, featured: false, genre: 'jazz' },
    { id: 6, date: '2026-04-10', name: 'Steel Thunder', description: 'Heavy metal concert.', artists: 'Iron Echo', venue_name: 'Forge Arena', start_time: '21:00', image_url: 'https://picsum.photos/seed/event6/600/400', ticket_link: 'https://tickets.com/event6', created_by: 4, featured: true, genre: 'metal' },
    { id: 7, date: '2026-04-11', name: 'Pop Explosion', description: 'Pop music party.', artists: 'Starlight', venue_name: 'City Hall Stage', start_time: '20:30', image_url: 'https://picsum.photos/seed/event7/600/400', ticket_link: 'https://tickets.com/event7', created_by: 5, featured: false, genre: 'pop' },
    { id: 8, date: '2026-04-12', name: 'Unplugged Nights', description: 'Acoustic session.', artists: 'River Lane', venue_name: 'The Lantern', start_time: '19:30', image_url: 'https://picsum.photos/seed/event8/600/400', ticket_link: 'https://tickets.com/event8', created_by: 6, featured: false, genre: 'acoustic' },
    { id: 9, date: '2026-04-13', name: 'Bassline City', description: 'Deep bass electronic.', artists: 'DJ Voltage', venue_name: 'Pulse Warehouse', start_time: '23:00', image_url: 'https://picsum.photos/seed/event9/600/400', ticket_link: 'https://tickets.com/event9', created_by: 7, featured: true, genre: 'electronic' },
    { id: 10, date: '2026-04-14', name: 'Garage Revival', description: 'Garage rock revival.', artists: 'The Sparks', venue_name: 'Rusty Garage', start_time: '20:00', image_url: 'https://picsum.photos/seed/event10/600/400', ticket_link: 'https://tickets.com/event10', created_by: 8, featured: false, genre: 'rock' },
    { id: 11, date: '2026-04-15', name: 'Street Cypher', description: 'Freestyle rap battles.', artists: 'MC Drift', venue_name: 'Downtown Stage', start_time: '21:45', image_url: 'https://picsum.photos/seed/event11/600/400', ticket_link: 'https://tickets.com/event11', created_by: 9, featured: false, genre: 'hiphop' },
    { id: 12, date: '2026-04-16', name: 'Indie Waves', description: 'Dreamy indie rock.', artists: 'Silver Coast', venue_name: 'Ocean Hall', start_time: '19:45', image_url: 'https://picsum.photos/seed/event12/600/400', ticket_link: 'https://tickets.com/event12', created_by: 2, featured: false, genre: 'rock' },
    { id: 13, date: '2026-04-17', name: 'Digital Dreams', description: 'Late night synth.', artists: 'DJ Aurora', venue_name: 'Neon Warehouse', start_time: '22:30', image_url: 'https://picsum.photos/seed/event13/600/400', ticket_link: 'https://tickets.com/event13', created_by: 3, featured: true, genre: 'electronic' },
    { id: 14, date: '2026-04-18', name: 'Late Night Jazz', description: 'Jazz improvisation.', artists: 'Moonlight Quartet', venue_name: 'Velvet Lounge', start_time: '21:00', image_url: 'https://picsum.photos/seed/event14/600/400', ticket_link: 'https://tickets.com/event14', created_by: 4, featured: false, genre: 'jazz' },
    { id: 15, date: '2026-04-19', name: 'Dark Forge', description: 'Heavy metal night.', artists: 'Crimson Steel', venue_name: 'Forge Arena', start_time: '22:15', image_url: 'https://picsum.photos/seed/event15/600/400', ticket_link: 'https://tickets.com/event15', created_by: 5, featured: false, genre: 'metal' },
    { id: 16, date: '2026-04-20', name: 'Summer Pop Fest', description: 'Pop festival.', artists: 'Neon Hearts', venue_name: 'Sunset Arena', start_time: '20:30', image_url: 'https://picsum.photos/seed/event16/600/400', ticket_link: 'https://tickets.com/event16', created_by: 6, featured: true, genre: 'pop' },
    { id: 17, date: '2026-04-21', name: 'Campfire Sessions', description: 'Acoustic storytelling.', artists: 'Oak & Ember', venue_name: 'Forest Pavilion', start_time: '18:45', image_url: 'https://picsum.photos/seed/event17/600/400', ticket_link: 'https://tickets.com/event17', created_by: 7, featured: false, genre: 'acoustic' },
    { id: 18, date: '2026-04-22', name: 'Future Frequency', description: 'Experimental electronic.', artists: 'DJ Signal', venue_name: 'Pulse Warehouse', start_time: '23:30', image_url: 'https://picsum.photos/seed/event18/600/400', ticket_link: 'https://tickets.com/event18', created_by: 8, featured: false, genre: 'electronic' },
    { id: 19, date: '2026-04-23', name: 'Thunder Stage', description: 'Big rock stage.', artists: 'Stormbreak', venue_name: 'Grand Arena', start_time: '21:15', image_url: 'https://picsum.photos/seed/event19/600/400', ticket_link: 'https://tickets.com/event19', created_by: 9, featured: true, genre: 'rock' },
    { id: 20, date: '2026-04-24', name: 'Beat District', description: 'Hip hop showcase.', artists: 'Flow State', venue_name: 'Downtown Stage', start_time: '22:00', image_url: 'https://picsum.photos/seed/event20/600/400', ticket_link: 'https://tickets.com/event20', created_by: 10, featured: false, genre: 'hiphop' }
  ]);
};
 