export async function seed(knex) {
  await knex('event').insert([
    { 
      id: 1, 
      date: '2026-06-05', 
      name: 'Midnight Riot', 
      description: 'High energy rock show.', 
      artists: 'Midnight Riot', 
      venue_name: 'The Civic', 
      address: '269-287 Queen Street, Auckland CBD, Auckland 1010',
      lat: -36.8523,
      lng: 174.7645,
      start_time: '20:00', 
      image_url: 'https://picsum.photos/seed/event1/600/400', 
      ticket_link: 'https://tickets.com/event1', 
      created_by: 1, 
      featured: true, 
      genre: 'rock' 
    },
    { 
      id: 2, 
      date: '2026-06-06', 
      name: 'Neon Pulse', 
      description: 'Electronic DJ night.', 
      artists: 'DJ Pulse', 
      venue_name: 'Underground Lounge', 
      address: '159 Karangahape Road, Auckland CBD, Auckland 1010',
      lat: -36.8584,
      lng: 174.7592,
      start_time: '21:30', 
      image_url: 'https://picsum.photos/seed/event2/600/400', 
      ticket_link: 'https://tickets.com/event2', 
      created_by: 2, 
      featured: true, 
      genre: 'electronic' 
    },
    { 
      id: 3, 
      date: '2026-06-07', 
      name: 'Indie Garden', 
      description: 'Relaxed indie gig.', 
      artists: 'The Ferns', 
      venue_name: 'Harbour Stage', 
      address: 'Customhouse Quay, Wellington Central, Wellington 6011',
      lat: -41.2825,
      lng: 174.7787,
      start_time: '19:00', 
      image_url: 'https://picsum.photos/seed/event3/600/400', 
      ticket_link: 'https://tickets.com/event3', 
      created_by: 1, 
      featured: false, 
      genre: 'rock' 
    },
    { 
      id: 4, 
      date: '2026-06-08', 
      name: 'Urban Flow', 
      description: 'Hip hop showcase.', 
      artists: 'MC Nova', 
      venue_name: 'San Fran', 
      address: '171 Cuba Street, Te Aro, Wellington 6011',
      lat: -41.2941,
      lng: 174.7749,
      start_time: '22:00', 
      image_url: 'https://picsum.photos/seed/event4/600/400', 
      ticket_link: 'https://tickets.com/event4', 
      created_by: 3, 
      featured: false, 
      genre: 'hiphop' 
    },
    { 
      id: 5, 
      date: '2026-06-09', 
      name: 'Blue Note Sessions', 
      description: 'Smooth jazz night.', 
      artists: 'Blue Note Trio', 
      venue_name: 'The Darkroom', 
      address: '336 St Asaph Street, Christchurch Central City, Christchurch 8011',
      lat: -43.5359,
      lng: 172.6455,
      start_time: '18:30', 
      image_url: 'https://picsum.photos/seed/event5/600/400', 
      ticket_link: 'https://tickets.com/event5', 
      created_by: 2, 
      featured: false, 
      genre: 'jazz' 
    },
    { 
      id: 6, 
      date: '2026-06-10', 
      name: 'Steel Thunder', 
      description: 'Heavy metal concert.', 
      artists: 'Iron Echo', 
      venue_name: 'Forge Arena', 
      address: '601 Great South Road, Ellerslie, Auckland 1051',
      lat: -36.8988,
      lng: 174.8058,
      start_time: '21:00', 
      image_url: 'https://picsum.photos/seed/event6/600/400', 
      ticket_link: 'https://tickets.com/event6', 
      created_by: 4, 
      featured: true, 
      genre: 'metal' 
    },
    { 
      id: 7, 
      date: '2026-06-11', 
      name: 'Pop Explosion', 
      description: 'Pop music party.', 
      artists: 'Starlight', 
      venue_name: 'City Hall Stage', 
      address: '1 Greys Avenue, Auckland CBD, Auckland 1010',
      lat: -36.8531,
      lng: 174.7633,
      start_time: '20:30', 
      image_url: 'https://picsum.photos/seed/event7/600/400', 
      ticket_link: 'https://tickets.com/event7', 
      created_by: 5, 
      featured: false, 
      genre: 'pop' 
    },
    { 
      id: 8, 
      date: '2026-06-12', 
      name: 'Unplugged Nights', 
      description: 'Acoustic session.', 
      artists: 'River Lane', 
      venue_name: 'The Lantern', 
      address: '31 Northcroft Street, Takapuna, Auckland 0622',
      lat: -36.7885,
      lng: 174.7705,
      start_time: '19:30', 
      image_url: 'https://picsum.photos/seed/event8/600/400', 
      ticket_link: 'https://tickets.com/event8', 
      created_by: 6, 
      featured: false, 
      genre: 'acoustic' 
    },
    { 
      id: 9, 
      date: '2026-06-13', 
      name: 'Bassline City', 
      description: 'Deep bass electronic.', 
      artists: 'DJ Voltage', 
      venue_name: 'Pulse Warehouse', 
      address: '42 Highfield Terrace, Mount Albert, Auckland 1025',
      lat: -36.8912,
      lng: 174.7214,
      start_time: '23:00', 
      image_url: 'https://picsum.photos/seed/event9/600/400', 
      ticket_link: 'https://tickets.com/event9', 
      created_by: 7, 
      featured: true, 
      genre: 'electronic' 
    },
    { 
      id: 10, 
      date: '2026-06-14', 
      name: 'Garage Revival', 
      description: 'Garage rock revival.', 
      artists: 'The Sparks', 
      venue_name: 'Rusty Garage', 
      address: '12 Bond Street, Arch Hill, Auckland 1021',
      lat: -36.8688,
      lng: 174.7455,
      start_time: '20:00', 
      image_url: 'https://picsum.photos/seed/event10/600/400', 
      ticket_link: 'https://tickets.com/event10', 
      created_by: 8, 
      featured: false, 
      genre: 'rock' 
    },
    { 
      id: 11, 
      date: '2026-06-15', 
      name: 'Street Cypher', 
      description: 'Freestyle rap battles.', 
      artists: 'MC Drift', 
      venue_name: 'Downtown Stage', 
      address: 'Britomart Place, Auckland CBD, Auckland 1010',
      lat: -36.8454,
      lng: 174.7708,
      start_time: '21:45', 
      image_url: 'https://picsum.photos/seed/event11/600/400', 
      ticket_link: 'https://tickets.com/event11', 
      created_by: 9, 
      featured: false, 
      genre: 'hiphop' 
    },
    { 
      id: 12, 
      date: '2026-06-16', 
      name: 'Indie Waves', 
      description: 'Dreamy indie rock.', 
      artists: 'Silver Coast', 
      venue_name: 'Ocean Hall', 
      address: 'Tamaki Drive, Mission Bay, Auckland 1071',
      lat: -36.8488,
      lng: 174.8322,
      start_time: '19:45', 
      image_url: 'https://picsum.photos/seed/event12/600/400', 
      ticket_link: 'https://tickets.com/event12', 
      created_by: 2, 
      featured: false, 
      genre: 'rock' 
    },
    { 
      id: 13, 
      date: '2026-06-17', 
      name: 'Digital Dreams', 
      description: 'Late night synth.', 
      artists: 'DJ Aurora', 
      venue_name: 'Neon Warehouse', 
      address: '15 Ian McKinnon Drive, Eden Terrace, Auckland 1010',
      lat: -36.8665,
      lng: 174.7544,
      start_time: '22:30', 
      image_url: 'https://picsum.photos/seed/event13/600/400', 
      ticket_link: 'https://tickets.com/event13', 
      created_by: 3, 
      featured: true, 
      genre: 'electronic' 
    },
    { 
      id: 14, 
      date: '2026-06-18', 
      name: 'Late Night Jazz', 
      description: 'Jazz improvisation.', 
      artists: 'Moonlight Quartet', 
      venue_name: 'Velvet Lounge', 
      address: '5 Cross Street, Auckland CBD, Auckland 1010',
      lat: -36.8582,
      lng: 174.7598,
      start_time: '21:00', 
      image_url: 'https://picsum.photos/seed/event14/600/400', 
      ticket_link: 'https://tickets.com/event14', 
      created_by: 4, 
      featured: false, 
      genre: 'jazz' 
    },
    { 
      id: 15, 
      date: '2026-06-19', 
      name: 'Dark Forge', 
      description: 'Heavy metal night.', 
      artists: 'Crimson Steel', 
      venue_name: 'Forge Arena', 
      address: '601 Great South Road, Ellerslie, Auckland 1051',
      lat: -36.8988,
      lng: 174.8058,
      start_time: '22:15', 
      image_url: 'https://picsum.photos/seed/event15/600/400', 
      ticket_link: 'https://tickets.com/event15', 
      created_by: 5, 
      featured: false, 
      genre: 'metal' 
    },
    { 
      id: 16, 
      date: '2026-06-20', 
      name: 'Summer Pop Fest', 
      description: 'Pop festival.', 
      artists: 'Neon Hearts', 
      venue_name: 'Sunset Arena', 
      address: '80 Mahuhu Crescent, Auckland CBD, Auckland 1010',
      lat: -36.8485,
      lng: 174.7766,
      start_time: '20:30', 
      image_url: 'https://picsum.photos/seed/event16/600/400', 
      ticket_link: 'https://tickets.com/event16', 
      created_by: 6, 
      featured: true, 
      genre: 'pop' 
    },
    { 
      id: 17, 
      date: '2026-06-21', 
      name: 'Campfire Sessions', 
      description: 'Acoustic storytelling.', 
      artists: 'Oak & Ember', 
      venue_name: 'Forest Pavilion', 
      address: 'Domain Drive, Grafton, Auckland 1010',
      lat: -36.8601,
      lng: 174.7752,
      start_time: '18:45', 
      image_url: 'https://picsum.photos/seed/event17/600/400', 
      ticket_link: 'https://tickets.com/event17', 
      created_by: 7, 
      featured: false, 
      genre: 'acoustic' 
    },
    { 
      id: 18, 
      date: '2026-06-22', 
      name: 'Future Frequency', 
      description: 'Experimental electronic.', 
      artists: 'DJ Signal', 
      venue_name: 'Pulse Warehouse', 
      address: '42 Highfield Terrace, Mount Albert, Auckland 1025',
      lat: -36.8912,
      lng: 174.7214,
      start_time: '23:30', 
      image_url: 'https://picsum.photos/seed/event18/600/400', 
      ticket_link: 'https://tickets.com/event18', 
      created_by: 8, 
      featured: false, 
      genre: 'electronic' 
    },
    { 
      id: 19, 
      date: '2026-06-23', 
      name: 'Thunder Stage', 
      description: 'Big rock stage.', 
      artists: 'Stormbreak', 
      venue_name: 'Grand Arena', 
      address: '764 Great South Road, Wiri, Auckland 2104',
      lat: -37.0055,
      lng: 174.8698,
      start_time: '21:15', 
      image_url: 'https://picsum.photos/seed/event19/600/400', 
      ticket_link: 'https://tickets.com/event19', 
      created_by: 9, 
      featured: true, 
      genre: 'rock' 
    },
    { 
      id: 20, 
      date: '2026-06-24', 
      name: 'Beat District', 
      description: 'Hip hop showcase.', 
      artists: 'Flow State', 
      venue_name: 'Downtown Stage', 
      address: 'Britomart Place, Auckland CBD, Auckland 1010',
      lat: -36.8454,
      lng: 174.7708,
      start_time: '22:00', 
      image_url: 'https://picsum.photos/seed/event20/600/400', 
      ticket_link: 'https://tickets.com/event20', 
      created_by: 10, 
      featured: false, 
      genre: 'hiphop' 
    }
  ]);
};
